
package ru.bodrov.gallery.service.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IPicture", targetNamespace = "http://servicews.service.gallery.bodrov.ru/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IPicture {


    /**
     * 
     * @param arg0
     * @return
     *     returns ru.bodrov.gallery.service.client.PictureDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPictureByTitle", targetNamespace = "http://servicews.service.gallery.bodrov.ru/", className = "ru.bodrov.gallery.service.client.GetPictureByTitle")
    @ResponseWrapper(localName = "getPictureByTitleResponse", targetNamespace = "http://servicews.service.gallery.bodrov.ru/", className = "ru.bodrov.gallery.service.client.GetPictureByTitleResponse")
    @Action(input = "http://servicews.service.gallery.bodrov.ru/IPicture/getPictureByTitleRequest", output = "http://servicews.service.gallery.bodrov.ru/IPicture/getPictureByTitleResponse")
    public PictureDTO getPictureByTitle(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns ru.bodrov.gallery.service.client.ResultDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "removePictureById", targetNamespace = "http://servicews.service.gallery.bodrov.ru/", className = "ru.bodrov.gallery.service.client.RemovePictureById")
    @ResponseWrapper(localName = "removePictureByIdResponse", targetNamespace = "http://servicews.service.gallery.bodrov.ru/", className = "ru.bodrov.gallery.service.client.RemovePictureByIdResponse")
    @Action(input = "http://servicews.service.gallery.bodrov.ru/IPicture/removePictureByIdRequest", output = "http://servicews.service.gallery.bodrov.ru/IPicture/removePictureByIdResponse")
    public ResultDTO removePictureById(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns ru.bodrov.gallery.service.client.PictureDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPictureByTypeId", targetNamespace = "http://servicews.service.gallery.bodrov.ru/", className = "ru.bodrov.gallery.service.client.GetPictureByTypeId")
    @ResponseWrapper(localName = "getPictureByTypeIdResponse", targetNamespace = "http://servicews.service.gallery.bodrov.ru/", className = "ru.bodrov.gallery.service.client.GetPictureByTypeIdResponse")
    @Action(input = "http://servicews.service.gallery.bodrov.ru/IPicture/getPictureByTypeIdRequest", output = "http://servicews.service.gallery.bodrov.ru/IPicture/getPictureByTypeIdResponse")
    public PictureDTO getPictureByTypeId(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns ru.bodrov.gallery.service.client.ResultDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addNewPicture", targetNamespace = "http://servicews.service.gallery.bodrov.ru/", className = "ru.bodrov.gallery.service.client.AddNewPicture")
    @ResponseWrapper(localName = "addNewPictureResponse", targetNamespace = "http://servicews.service.gallery.bodrov.ru/", className = "ru.bodrov.gallery.service.client.AddNewPictureResponse")
    @Action(input = "http://servicews.service.gallery.bodrov.ru/IPicture/addNewPictureRequest", output = "http://servicews.service.gallery.bodrov.ru/IPicture/addNewPictureResponse")
    public ResultDTO addNewPicture();

    /**
     * 
     * @param arg0
     * @return
     *     returns ru.bodrov.gallery.service.client.PictureDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPictureById", targetNamespace = "http://servicews.service.gallery.bodrov.ru/", className = "ru.bodrov.gallery.service.client.GetPictureById")
    @ResponseWrapper(localName = "getPictureByIdResponse", targetNamespace = "http://servicews.service.gallery.bodrov.ru/", className = "ru.bodrov.gallery.service.client.GetPictureByIdResponse")
    @Action(input = "http://servicews.service.gallery.bodrov.ru/IPicture/getPictureByIdRequest", output = "http://servicews.service.gallery.bodrov.ru/IPicture/getPictureByIdResponse")
    public PictureDTO getPictureById(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<ru.bodrov.gallery.service.client.PictureDTO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getListPicture", targetNamespace = "http://servicews.service.gallery.bodrov.ru/", className = "ru.bodrov.gallery.service.client.GetListPicture")
    @ResponseWrapper(localName = "getListPictureResponse", targetNamespace = "http://servicews.service.gallery.bodrov.ru/", className = "ru.bodrov.gallery.service.client.GetListPictureResponse")
    @Action(input = "http://servicews.service.gallery.bodrov.ru/IPicture/getListPictureRequest", output = "http://servicews.service.gallery.bodrov.ru/IPicture/getListPictureResponse")
    public List<PictureDTO> getListPicture();

}
